import React from "react";
import styles from "./legal.module.css";

const TermsOfUse = () => {
  return (
    <>
      <h1 className="h4">TERM OF USE</h1>

      <br />

      <p className={styles.bold}>
        Welcome to LEONDEVS TECH (OPC) PRIVATE LIMITED’s Terms of Use
      </p>

      <br />

      <p>
        We LEONDEVS TECH (OPC) PRIVATE LIMITED, are designed to serve as a B2B
        Custom Software Development Service Provider. This website is owned and
        operated by M/s. LEONDEVS TECH (OPC) PRIVATE LIMITED (hereinafter
        referred to as “Company”) which operates its business under the same
        name “M/s. LEONDEVS TECH (OPC) PRIVATE LIMITED”. This Terms of Use
        (hereinafter referred to as “Terms of Use”) clearly explains the nature
        and operational workflow of the website. This Terms of Use lays down all
        the terms and conditions surrounding the usage of our Website for you
        and the Company.
      </p>

      <br />

      <p>
        Platform herein and in all associated policies refer to
        https://www.leondevs.tech/
      </p>

      <br />

      <p>
        Upon usage, registration, or even browsing through our Website creates a
        contractual relationship between you and us through this Terms of Use
        and other relevant policies associated with our Website, for all
        contractual, legal, and compliance purposes. This Terms of Use is
        considered as a legally binding agreement and is also considered as an
        electronic record in terms of the Information Technology Act, 2000 and
        rules thereunder as applicable and the amended provisions about
        electronic records in various statutes as amended by the Information
        Technology Act, 2000. This electronic record is generated by a computer
        system and does not require any physical or digital signatures.
      </p>

      <br />

      {/* DEFINATION AND INTERPRETATION */}

      <h2 className="h5">DEFINATION AND INTERPRETATION</h2>

      <ol type="1" className={styles.insetList1}>
        <li>
          <span className={styles.bold}>Defination</span>
          <ol type="a" className={styles.insetList2}>
            <li>
              <span className={styles.bold}>Applicable Laws -</span>shall mean
              and refer to all the laws, rules, ordinances, by-laws, etc., and
              amendments thereafter, applicable within the territory of India.
            </li>

            <li>
              <span className={styles.bold}>Content</span>- shall mean and refer
              to all the text, advertisement, graphics, User interfaces, visual
              interfaces, photographs, trademarks, logos, brand names,
              descriptions, sounds, music, and artwork.
            </li>

            <li>
              <span className={styles.bold}>Third Parties</span>- shall mean and
              refer to all the legal entities either individual or entity linked
              on the Website apart from the Users and the creator of this
              Website.
            </li>

            <li>
              <span className={styles.bold}>Servicce</span> - shall mean and
              refer to all the intermediary services provided by the Website to
              the User.
            </li>
          </ol>
        </li>

        <li>
          <span className={styles.bold}>Interpretation</span>

          <ol type="a" className={styles.insetList2}>
            <li>
              <span className={styles.bold}>Company</span>- For the purposes of
              this Terms of Use, wherever the context so requires,{" "}
              <span className={styles.italics}>“Company”, “We”, “Our”,</span>{" "}
              and “Us” shall mean and refer to the Company and the Website
              itself.
            </li>

            <li>
              <span className={styles.bold}>Platform</span>- For the purposes of
              this Terms of Use, the Website shall be referred to as the
              Platform, unless specified otherwise in this Terms of Use.
            </li>

            <li>
              <span className={styles.bold}>User</span>- For the purposes of
              this Terms of Use, wherever the context so requires,{" "}
              <span className={styles.italic}>
                “You”, “Your”, “Yourself”, “User”,
              </span>{" "}
              and <span className={styles.italic}>“Customer”</span>
              shall mean and refer to natural and legal individuals who shall be
              users of this Website provided by Us and who is competent to enter
              into binding contracts, as per law.
            </li>

            <li>
              The headings of each section in these Terms of Use are only for
              the purpose of organizing the various provisions under these Terms
              of Use in an orderly manner and shall not be used by you to
              interpret the provisions contained herein in a manner as may apply
              to you. Further, it is specifically agreed by you that the
              headings shall not have legal or contractual value on your usage
              of the Website.
            </li>

            <li>
              The Parties shall refer and mean the Company and User together,
              for the purpose of interpretation of terms of this Terms of Use.
            </li>

            <li>
              The use of this Website is solely governed by these Terms of Use,
              Privacy Policy, and any other relevant policies as updated on the
              Website and any modifications or amendments made thereto by us
              from time to time, at our sole discretion. By continuing to access
              or use this Website, you acknowledge and agree to be bound by
              these Terms of Use, the Privacy Policy, and any other applicable
              policies governing the Website.
            </li>

            <li>
              You expressly agree and acknowledge that these Terms of Use and
              Privacy Policy, and any other applicable policies, are co-terminus
              in nature and that expiry/termination of either one will lead to
              the termination of the other.
            </li>

            <li>
              You unequivocally agree that these Terms of Use, Privacy Policy,
              and any other applicable policies, constitute a legally binding
              agreement between us and that you shall be subject to the rules,
              guidelines, policies, terms, and conditions applicable to your use
              of the Platform, and that the same shall be deemed to be
              incorporated into these Terms of Use and shall be treated as part
              and parcel of the same. You acknowledge and agree that no
              signature or express act is required to make these Terms of Use
              and the Privacy Policy binding on you and that your act of
              visiting/browsing any part of the Website constitutes your full
              and final acceptance of these Terms of Use, Privacy Policy, and
              any other applicable policies.
            </li>

            <li>
              We reserve the sole and exclusive right to amend or modify these
              Terms of Use without any prior permission or intimation to you,
              and you expressly agree that any such amendments or modifications
              shall come into effect immediately. If you do not adhere to the
              changes, you must stop using the Website at once. Your continued
              use of the Website will signify your acceptance of the changed
              Terms of Use.
            </li>
          </ol>
        </li>
      </ol>

      <br />

      {/* PLATFORM OVERVIEW */}
      <h2 className="h5">PLATFORM OVERVIEW</h2>

      <br />

      <p>
        LEONDEVS TECH (OPC) PRIVATE LIMITED is a company incorporated under the
        Companies Act, 2013, with its registered office at No. A-81, Jeevan
        Vihar, Shastri Nagar, Ghaziabad, Uttar Pradesh – 201002 (hereinafter
        referred to as the “Company”). The Company operates as a B2B technology
        partner, offering professional services in custom web and mobile
        application development, as well as web page and UI/UX design tailored
        to the unique needs of its business clients.
      </p>

      <br />

      <p>
        The Platform, accessible at https://www.leondevs.tech, serves as a
        digital business interface to:
      </p>

      <ol type="1" className={styles.insetList1}>
        <li>
          Showcase the Company’s portfolio, technological capabilities, and
          design expertise;
        </li>

        <li>Provide details about the services offered;</li>

        <li>
          Enable potential clients to initiate contact and submit business
          inquiries.
        </li>
      </ol>

      <br />

      <p>
        The Platform is intended exclusively for business users such as
        start-ups, SMEs, and enterprises and is not designed for consumer-facing
        services or public user interaction. No software or services are
        delivered directly through the Platform. All client engagements are
        formalized through agreements, and the actual delivery of services (such
        as deployment of applications, transfer of source code and design files)
        takes place via third-party tools like GitHub or other secure
        file-sharing systems.
      </p>

      <br />

      <p>Visitors to the website can:</p>

      <ul className={styles.insetList1}>
        <li>Explore case studies and service descriptions;</li>

        <li>
          Access official contact information including email, business
          messaging, and location;
        </li>

        <li>
          Understand the end-to-end scope of web and app development and design
          services offered by the Company.
        </li>
      </ul>

      <br />

      <p>Registered users (via Google Sign-In) may:</p>

      <ul className={styles.insetList1}>
        <li>Submit prospective business leads;</li>

        <li>Participate in referral programs, subject to verification;</li>

        <li>
          Manage limited business-related information relevant to referrals or
          project onboarding.
        </li>
      </ul>

      <br />

      <p>
        The Platform does not support payments, social interaction, or content
        sharing among users. It functions solely as a professional gateway for
        businesses to learn about and engage with the Company’s development and
        design services.
      </p>

      <br />

      <p>
        <span className={styles.bold}>Target Audience -</span>
        The primary target audience of the Platform is business entities (B2B),
        including but not limited to:
      </p>

      <ul className={styles.insetList1}>
        <li>
          Start-ups seeking end-to-end product development or MVP builds;{" "}
        </li>

        <li>
          Small and Medium Enterprises (SMEs) looking to digitize operations
          through tailored web or mobile applications;
        </li>

        <li>
          Established Enterprises requiring scalable frontend, backend, or
          e-commerce solutions;
        </li>

        <li>
          Agencies or consulting firms collaborating on technical delivery
          through white-label or subcontracting models.
        </li>
      </ul>

      <br />
      <p>
        While the services offered by LEONDEVS TECH (OPC) PRIVATE LIMITED are
        structured and delivered exclusively within a B2B engagement framework,{" "}
        <span className={styles.bold}>
          the Platform itself may be accessed by any visitor.
        </span>{" "}
        This includes individuals or non-commercial users who may browse
        publicly available content such as the portfolio, service descriptions,
        or contact details.
      </p>

      <br />

      <p>However, it is important to note:</p>

      <ul className={styles.insetList1}>
        <li>
          All formal engagements are business-driven and executed through
          contractual agreements;
        </li>

        <li>Service delivery is not provided via the Platform;</li>

        <li>
          General users (non-business) may not be eligible for certain features
          such as lead submission, referral programs, or commercial onboarding;
        </li>

        <li>
          The Platform does not serve consumers/end-users in a personal capacity
          and does not offer direct-to-consumer tools or interfaces.
        </li>
      </ul>

      <br />

      {/* LEGAL FRAMEWORK AND COMPLIANCE */}
      <h2 className="h5">LEGAL FRAMEWORK AND COMPLIANCE</h2>

      <br />

      <p>
        This Terms of Use is made in accordance with the provisions of the{" "}
        <span className={styles.bold}>
          Information and Technology Act, 2000
        </span>{" "}
        and the rules therein under along with the amendment from time to time.
        This Terms of Use is published on the Platform in accordance with the
        provisions of Rule 3 (1) of the Information Technology (Intermediaries
        guidelines) Rules, 2011 and Rule 4 of the Information Technology
        (Reasonable Security Practices and Procedures and Sensitive Personal
        Data or Information) Rules, 2011 of Information Technology Act, 2000
        amended through Information Technology Amendment Act, 2008 that require
        publishing the Terms of Use and practices for access and usage of any
        functional Website.
      </p>

      <br />

      {/* WORKFLOW OF OPERATION OF PLATFORM */}
      <h2 className="h5">WORKFLOW OF OPERATION OF PLATFORM</h2>

      <br />

      <p>
        The Platform (https://www.leondevs.tech) is designed to facilitate
        structured business engagement and professional onboarding of clients
        interested in frontend, backend, and e-commerce development services.
        The operational flow is as follows:
      </p>

      <ol type="1" className={styles.insetList1}>
        <li>
          <span className={styles.bold}>
            Public Visitors (No Sign-In Required):
          </span>{" "}
          Any business visitor accessing the Platform can:
          <ol type="a" className={styles.insetList2}>
            <li>Review the Company’s service offerings, which include:</li>

            <ol type="i" className={styles.insetList3}>
              <li>
                <span className={styles.bold}>Frontend Solutions:</span>{" "}
                Development of responsive, efficient, and well-structured
                client-facing applications using React.js or Next.js, depending
                on project needs;
              </li>

              <li>
                <span className={styles.bold}>Backend Solutions:</span>{" "}
                Server-side development, including API servers and business
                logic implementation using Node.js and Express.js;
              </li>

              <li>
                <span className={styles.bold}>E-Commerce Solutions:</span>{" "}
                Full-stack solutions specifically tailored for online commerce,
                built with a scalable backend architecture.
              </li>
            </ol>

            <li>View project showcases and technical expertise;</li>

            <li>
              Access the Company’s official contact information including email
              address, location, and messaging channels.
            </li>
          </ol>
          <br />
          <p>
            This information is available openly to help potential business
            clients evaluate the Company’s capabilities before initiating a
            business inquiry.
          </p>
          <br />
        </li>

        <li>
          <span className={styles.bold}>
            Registered Users (Google Sign-In):
          </span>{" "}
          Business users who authenticate using Google Sign-In may:
        </li>

        <ol type="a" className={styles.insetList2}>
          <li>
            Submit qualified business leads, including details such as company
            name, nature of requirement, and contact details of the prospective
            client;
          </li>

          <li>
            Participate in the referral program (subject to eligibility), which
            may require PAN and bank account details for processing rewards;
          </li>

          <li>
            Maintain and update their profile information used for lead
            submission or referral tracking.
          </li>
        </ol>

        <br />

        <p>
          The data submitted is used strictly for internal evaluation and
          communication. It is not shared publicly or with other users.
        </p>

        <br />

        <li>
          <span>Post-Submission Engagement:</span> Once a lead or referral is
          received:
          <ol type="a" className={styles.insetList2}>
            <li>
              The Company reviews the submission and may reach out to the
              prospective client or the referring party for further details;
            </li>

            <li>
              Upon mutual agreement, a formal agreement is signed between the
              Company and the client;
            </li>

            <li>
              The actual design and development work — whether for frontend
              applications, backend infrastructure, or e-commerce systems — is
              carried out using secure third-party tools (such as GitHub,
              project management software, or deployment platforms).
            </li>
          </ol>
        </li>
      </ol>

      <br />

      <p>
        At no stage does the Platform support online payments, real-time service
        delivery, or public content sharing. Its primary role is to act as a
        professional interface for business discovery, lead intake, and project
        initiation.
      </p>

      <br />

      {/* ELIGIBILITY */}
      <h2 className="h5">ELIGIBILITY</h2>

      <br />

      <ol type="1" className={styles.insetList1}>
        <li>
          You represent and warrant that you are competent and eligible to enter
          into legally binding agreements and of competent age and that you have
          the requisite authority to bind yourself/themselves to these Terms of
          Use as per the Applicable Law. However, if you are a minor using this
          Website, you may do so with the consent of your legal guardian. All
          Acts of the minor shall be deemed to be considered as the acts
          undertaken under the supervision of their parent or legal guardian, as
          the case may be.
        </li>

        <li>
          The services offered by M/s. LEONDEVS TECH (OPC) PRIVATE LIMITED are
          intended for use by individuals who are at least 18 years of age.
          Users under the age of 18 must access the website and use services
          only under the supervision of a parent or legal guardian. By using the
          platform, you represent and warrant that you meet the eligibility
          requirements.
        </li>

        <li>
          You further represent that you will comply with these Terms of Use and
          all applicable local, state, national, and international laws, rules,
          and regulations.
        </li>

        <li>
          You shall not use the Website if you are not competent to enter into a
          contract or are disqualified from doing so by any other Applicable
          Laws, rule, or regulation, currently in force.
        </li>
      </ol>

      <br />

      {/* CONTENT */}
      <h2 className="h5">CONTENT</h2>

      <br />

      <ol className={styles.insetList1}>
        <li>
          Users may upload content, including but not limited to images, videos,
          audio files, and documents ("User Content"). While you retain all
          ownership rights in your content, by submitting User Content, you
          grant LEONDEVS TECH (OPC) PRIVATE LIMITED a non-exclusive,
          royalty-free, worldwide, and sub-licensable license to use, reproduce,
          display, and distribute the content for the sole purpose of providing
          and improving the platform and its services. You are responsible for
          ensuring that your content does not violate any applicable law or
          infringe on third-party rights.
        </li>

        <li>
          You are solely responsible for the integrity, authenticity, quality,
          and/or genuineness of the Content provided by you on the Platform and
          whilst feedback and comments by You can be made via the Website, we
          bear no liability whatsoever for any feedback or comments made by the
          other Users or made in respect of any of the Content on the Platform.
          Further, the Company reserves the right to suspend the account of any
          User for an indefinite period to be decided at the discretion of the
          Company or to terminate the account of any User who is found to have
          created or shared or submitted any Content or part thereof that is
          found to be untrue/ inaccurate/ misleading/ offensive/ vulgar. You
          shall be solely responsible for making good any financial or legal
          losses incurred through the creation/ sharing/ submission of Content
          or part thereof that is deemed to be untrue/ inaccurate/ misleading/
          offensive/ vulgar.
        </li>

        <li>
          You have a personal, non-exclusive, non-transferable, revocable,
          limited privilege to access the Content on the Platform. You shall not
          copy, adapt, and modify any Content without written permission from
          the Company.
        </li>

        <li>
          All website content (text, graphics, logos, code, design) is owned by
          LEONDEVS TECH (OPC) PRIVATE LIMITED. Portfolio case studies remain
          client-confidential; reproduction requires written consent from both
          LEONDEVS and the respective client. Users grant limited license to
          display uploaded prospect leads internally but retain ownership of
          original data.
        </li>

        <li>
          <span className={styles.bold}>Acceptable Content:</span>
          <ol type="a" className={styles.insetList2}>
            <li>Business contact emails</li>

            <li>Corporate phone numbers</li>

            <li>Industry classification data</li>
          </ol>
        </li>

        <li>Prohibited Content:</li>

        <ol className={styles.insetList2} type="a">
          <li>Personal consumer information (e.g., residential numbers)</li>

          <li>Financial/health records </li>

          <li>Copyrighted material without authorization </li>

          <li>Defamatory/political/religious statements</li>

          <li>Malware/executable files</li>
        </ol>

        <li>
          <span className={styles.bold}>Mandatory Warranties:</span> By
          submitting content, you affirm:
          <ol type="a" className={styles.insetList2}>
            <li>You have authority to share this business information</li>

            <li>Data complies with India's DPDPA 2023</li>

            <li>No third-party IP rights are violated</li>
          </ol>
        </li>
      </ol>

      <br />

      {/* INDEMNITY */}
      <h2 className="h5">INDEMNITY</h2>

      <br />

      <p>
        You agree to indemnify, defend and hold harmless the Company, and its
        respective directors, officers, employees, and agents (hereinafter
        collectively referred to as "Parties"), from and against any losses,
        liabilities, claims, damages, demands, costs, and expenses (including
        legal fees and disbursements in connection therewith and interest
        chargeable thereon) asserted against or incurred by us that arise out
        of, result from, or maybe payable by, any breach or non-performance of
        any representation, warranty, covenant, or agreement made or obligation
        to be performed according to these Terms of Use. Further, you agree to
        hold the Company harmless against any claims made by any Third Party due
        to/ or arising out of, or in connection with:
      </p>

      <ol type="1" className={styles.insetList1}>
        <li>Your use of the Website; </li>

        <li>Your violation of these Terms of Use; </li>

        <li>
          Your violation of any rights of another Parties, Users, and/or
          Third-Party;
        </li>

        <li>Your alleged improper conduct according to these Terms of Use</li>

        <li>Your conduct in connection with the Website.</li>
      </ol>

      <br />

      <p>
        You agree to fully cooperate in indemnifying the Company at your own
        expense. You also agree not to settle with any party without the consent
        of the Company.
      </p>

      <br />

      <p>
        In no event shall we be liable to compensate you or any Third Party for
        any special, incidental, indirect, consequential, or punitive damages
        whatsoever, including those resulting from loss of use, data, or
        profits, whether or not foreseeable, and whether or not you had been
        advised of the possibility of such damages, or based on any theory of
        liability, including breach of contract or warranty, negligence, or
        other tortuous action, or any other claim arising out of or in
        connection with your use of, or access, or availing Services from or
        materials contained therein on the Website.
      </p>

      <br />

      {/* LIMITATION OF LIABILITY */}
      <h2 className="h5">LIMITATION OF LIABILITY</h2>

      <br />

      <ol type="1" className={styles.insetList1}>
        <li>
          We are not responsible for any consequences arising out of the
          following events:
          <ol type="a" className={styles.insetList2}>
            <li>
              if the Website is inoperative/non-responsive due to any
              connectivity errors associated with the internet connection such
              as but not limited to slow connectivity, no connectivity, server
              failure;
            </li>

            <li>
              if you have fed incorrect information or data or for any deletion
              of data;
            </li>

            <li>
              if there is an undue delay or inability to communicate through
              email;
            </li>

            <li>
              if there is any deficiency or defect in the Services managed by
              the Company; and
            </li>

            <li>
              if there is a failure in the functioning of any other Service
              provided by the Company.
            </li>
          </ol>
        </li>

        <li>
          The Website accepts no liability for any errors or omissions, on
          behalf of itself, or for any damage caused to you, your belongings, or
          any Third-Party, resulting from the use or misuse of the Platform or
          any Service provided of by the Company through the Platform. The
          Service and any Content or material displayed of the Services are
          provided without any guarantees, conditions, or warranties as to its
          accuracy, suitability, completeness, or reliability. We will not be
          liable to you for the unavailability or failure of the Platform.
        </li>
        <li>
          You are to comply with all Applicable Laws upon you or on your
          activities, and with all applicable policies, which are hereby
          incorporated into this Terms of Use by reference.
        </li>
        <li>
          The Platform expressly excludes any liability for any loss or damage
          that was not reasonably foreseeable by the Website and which is
          incurred by you in connection with the Website, including loss of
          profits; and any loss or damage incurred by you as a result of your
          breach of these Terms of Use.
        </li>
        <li>
          To the fullest extent permitted by law, we shall not be liable to you
          or any other party for any loss or damage, regardless of the form of
          action or basis of any claim. You acknowledge and agree that your sole
          and exclusive remedy for any dispute with us is to terminate your use
          of the Website.
        </li>
      </ol>

      <br />

      {/* TERMS */}
      <h2 className="h5">TERMS</h2>
      <br />
      <ol type="1" className={styles.insetList1}>
        <li>
          These Terms of Use shall continue to form a valid and binding
          agreement between us and shall continue to be in full force and effect
          until you continue to access and use the Website.
        </li>
        <li>
          You may terminate your use of the Website at any time, as per the
          process specified under this Terms of Use.
        </li>
        <li>
          We may terminate these Terms of Use with you and close your account at
          any time without notice and/or suspend or terminate Your access to the
          Website at any time and for any reason if any discrepancy or legal
          issue arises.
        </li>
        <li>
          Such suspension or termination shall not limit our right to take any
          other action against you that we consider appropriate.
        </li>
        <li>
          It is also hereby declared that we may discontinue the Services on the
          Website without any prior notice.
        </li>
      </ol>

      <br />

      {/* TERMINATION */}
      <h2 className="h5">TERMINATION</h2>

      <br />

      <ol type="1" className={styles.insetList1}>
        <li>
          By using this Website and providing your identity and contact
          information to the Company through the Website, you agree and consent
          to receive e-mails or SMS from us and/or any of its representatives at
          any time.
        </li>
        <li>
          You can report to “mail@leondevs.tech” if you find any discrepancy
          with regard to Website or Content-related information and we will take
          necessary action after an investigation. The response with resolution
          (if any issues found) shall be dependent on the time is taken for
          investigation.
        </li>
        <li>
          You expressly agree that notwithstanding anything contained
          hereinabove, it may be contacted by us relating to any Services
          availed by you on the Website or anything pursuant thereto and you
          agree to indemnify us from any harassment claims. It is expressly
          agreed to by us that any information shared by us shall be governed by
          the Privacy Policy.
        </li>
        <li>
          You shall continue to be bound by these Terms of use, and it is
          expressly agreed to by You that You shall not have the right to
          terminate these Terms of Use till the expiry of the same.
        </li>
      </ol>

      <br />

      {/* COMMUNICATION */}
      <h2 className="h5">COMMUNICATION</h2>

      <br />

      <p>
        By using this Website and providing your identity and contact
        information to the Company through the Website, you agree and consent to
        receive e-mails or SMS from us and/or any of its representatives at any
        time.
      </p>

      <br />

      <p>
        You can report to “mail@leondevs.tech” if you find any discrepancy with
        regard to Website or Content-related information and we will take
        necessary action after an investigation. The response with resolution
        (if any issues found) shall be dependent on the time is taken for
        investigation.
      </p>

      <br />

      <p>
        You expressly agree that notwithstanding anything contained hereinabove,
        it may be contacted by us relating to any Services availed by you on the
        Website or anything pursuant thereto and you agree to indemnify us from
        any harassment claims. It is expressly agreed to by us that any
        information shared by us shall be governed by the Privacy Policy.
      </p>

      <br />

      {/* USER OBLIGATIONS AND FORMAL UNDERTAKING AS TO CONDUCT */}
      <h2 className="h5">
        USER OBLIGATIONS AND FORMAL UNDERTAKING AS TO CONDUCT
      </h2>

      <br />

      <p>
        You <span className={styles.bold}>agree</span> and{" "}
        <span className={styles.bold}>acknowledges</span> that you are a
        restricted user of this Platform and you:
      </p>

      <ol type="1" className={styles.insetList1}>
        <li>
          agree to provide genuine credentials during the process whenever
          required on the Website. You shall not use a fictitious identity. We
          are not liable if you have provided incorrect information;
        </li>

        <li>
          agree to ensure the Name, Email address, Phone Number, and any such
          other information that may be provided and is valid at all times and
          shall keep your information accurate and up-to-date;
        </li>

        <li>
          You agree that you are solely responsible for maintaining the
          confidentiality of your account. You agree to notify us immediately of
          any unauthorized use of your account. We reserve the right to close
          your account at any time for any or no reason;
        </li>

        <li>
          understand and acknowledge that the data submitted is manually entered
          into the database of the Platform. You also acknowledge the fact that
          data so entered into the database is for easy and ready reference for
          you, and to streamline the Services through the Website;
        </li>

        <li>
          authorize the Platform to use, store, or otherwise process certain
          personal information and all published Content, responses, locations,
          User comments, reviews, and ratings for personalization of Services,
          marketing, and promotional purposes, and for optimization of
          User-related options and Services;
        </li>

        <li>
          understand and agree that, to the fullest extent permissible by law,
          the Platform or any of their affiliates or their respective officers,
          directors, employees, agents, licensors, representatives, operational
          service providers, advertisers or suppliers shall not be liable for
          any loss or damage, of any kind, direct or indirect, in connection
          with or arising from the use of the Platform or this Terms of Use,
          including, but not limited to, compensatory, consequential,
          incidental, indirect, special or punitive damages;
        </li>

        <li>
          are bound not to cut, copy, modify, recreate, reverse engineer,
          distribute, disseminate, post, publish or create derivative works
          from, transfer, or sell any information or obtained from the Platform.
          Any such use/limited use of the Platform will only be allowed with the
          prior express written permission;
        </li>

        <li>
          agree not to access (or attempt to access) the Platform and/or the
          materials or Services by any means other than through the interface
          provided by the Platform. The use of deep-link, robot, spider or other
          automatic devices, program, algorithm or methodology, or any similar
          or equivalent manual process, to access, acquire, copy or monitor any
          portion of the Platform or its Content, or in any way reproduce or
          circumvent the navigational structure or presentation of the Platform,
          materials or any Content, or to obtain or attempt to obtain any
          materials, documents or information through any means not specifically
          made available through the Platform will lead to suspension or
          termination of your access to the Platform. We disclaim any
          liabilities arising concerning such offensive Content on the Platform;
          and
        </li>

        <li>
          expressly agree and acknowledge that the Content generated by the
          Users and displayed on the Platform is not owned by the Company and
          that we are in no way responsible for the Content of the same. You
          may, however, report any offensive or objectionable content, which we
          may then remove from the Platform, at our sole discretion.
        </li>

        <br />

        <p>
          {" "}
          You forther undertake <span className={styles.bold}>not</span> to :
        </p>

        <br />

        <li>
          engage in any activity that interferes with or disrupts access to the
          Platform or the Services provided therein (or the servers and networks
          which are connected to the Platform);
        </li>
        <li>
          impersonate any person or entity, or falsely state or otherwise
          misrepresent his/her affiliation with a person or entity;
        </li>
        <li>
          probe, scan, or test the vulnerability of the Platform or any network
          connected to the Platform, nor breach the security or authentication
          measures on the Platform or any network connected to the Platform. The
          User may not reverse look-up, trace, or seek to trace any information
          relating to any other User of, or visitor to the Platform, or any
          other viewer of the Platform, including any User account maintained on
          the Platform not operated/managed by the User, or exploit the Platform
          or information made available or offered by or through the Platform,
          in any manner;
        </li>
        <li>
          disrupt or interfere with the security of, or otherwise cause harm to
          the Platform, systems resources, accounts, passwords, servers, or
          networks connected to or accessible through the Platform or any
          affiliated or linked Platform;
        </li>
        <li>
          use the Platform or any material or Content therein for any purpose
          that is unlawful or prohibited by these Terms of Use, or to solicit
          the performance of any illegal activity or other activity which
          infringes the rights of this Platform or any other Third-Party(ies);
        </li>
        <li>
          violate any code of conduct or guideline which may apply for or to any
          particular Service offered through the Platform;
        </li>
        <li>
          violate any applicable laws, rules, or regulations currently in force
          within or outside India;
        </li>
        <li>
          violate any portion of these Terms of Use or the Privacy Policy,
          including but not limited to any applicable additional terms and
          conditions of the Platform contained herein or elsewhere, whether made
          by amendment, modification, or otherwise;
        </li>
        <li>
          commit any act that causes the Company to lose (in whole or in part)
          the Services of its Internet Establishment ("ISP") or in any manner
          disrupts the Services of any other supplier/service provider of the
          Platform;
        </li>
        <li>
          you hereby expressly authorize the Company to disclose any and all
          information relating to you in our possession to law enforcement or
          other government officials, as we may in our sole discretion, believe
          necessary or appropriate in connection with the investigation and/or
          resolution of possible crimes, especially those involve personal
          injury and theft/infringement of intellectual property. You further
          understand that the Platform might be directed to disclose any
          information (including the identity of persons providing information
          or materials on the Platform) as necessary to satisfy any judicial
          order, Applicable Law, regulation or valid governmental request;
        </li>
        <li>
          you agree to use the Services provided by the Company, our affiliates,
          consultants and contracted companies, for lawful purposes only;
        </li>
        <li>
          you agree to provide authentic and true information. We reserve the
          right to confirm and validate the information and other details
          provided by you at any point in time. If upon Confirmation such
          details are found to be false, not to be true (wholly or partly), we
          shall in our sole discretion reject the order and debar you from using
          the Platform without prior intimation whatsoever;
        </li>
        <li>
          you agree not to post any material on the Platform that is defamatory,
          offensive, obscene, indecent, abusive, or needlessly distressful, or
          advertising any goods or services. More specifically, you agree not to
          host, display, upload, update, publish, modify, transmit, or in any
          manner share any information that:
          <ol type="a" className={styles.insetList2}>
            <li>
              belongs to another person and to which you have no right to;
            </li>
            <li>
              is grossly harmful, harassing, blasphemous, defamatory, obscene,
              pornographic, pedophilic, libelous, invasive of another's privacy,
              hateful, or racially, ethnically objectionable, disparaging,
              relating or encouraging money laundering or gambling, or otherwise
              unlawful in any manner whatever;
            </li>
            <li>is in any way harmful to minors;</li>
            <li>
              infringes any patent, trademark, copyright or other proprietary
              rights;
            </li>
            <li>violates any Applicable Law for the time being in force;</li>
            <li>
              deceives or misleads the addressee about the origin of such
              messages or communicates any information which is grossly
              offensive or menacing;
            </li>
            <li>
              abuse, harass, threaten, defame, disillusion, erode, abrogate,
              demean or otherwise violate the legal rights of others;
            </li>
            <li>
              impersonate any person or entity, or falsely state or otherwise
              misrepresent your affiliation with a person or entity;
            </li>
            <li>
              publish, post, disseminate, any grossly harmful information,
              harassing, blasphemous, defamatory, obscene, pornographic,
              pedophilic, libelous, invasive of another 's privacy, hateful, or
              racially, ethnically objectionable, disparaging, relating or
              encouraging money laundering or gambling, or otherwise unlawful in
              any manner whatever; or unlawfully threatening or unlawfully
              harassing including but not limited to "indecent representation of
              women" within the meaning of the Indecent Representation of Women
              (Prohibition) Act, 1986; and
            </li>
            <li>
              threatens the unity, integrity, defence, security, or sovereignty
              of India, friendly relations with foreign states, or public order
              or causes incitement to the commission of any cognizable offence
              or prevents investigation of any offence or is insulting any other
              nation.
            </li>
          </ol>
        </li>
      </ol>

      <br />

      {/* SUSPENSION OF USER ACCESS AND ACTIVITY */}
      <h2 className="h5">SUSPENSION OF USER ACCESS AND ACTIVITY</h2>

      <br />

      <p>
        Notwithstanding other legal remedies that may be available, we may in
        our sole discretion, limit your access and/or activity by immediately
        removing your access credentials either temporarily or indefinitely, or
        suspend/terminate your association with the Platform, and/or refuse to
        the usage of the Platform, without being required to provide you with
        notice or cause
      </p>

      <ol type="1" className={styles.insetList1}>
        <li>
          if you are in breach of any of these Terms of Use, Privacy Policy, or
          any other applicable policies;
        </li>

        <li>
          if you have provided wrong, inaccurate, incomplete or incorrect
          information; and
        </li>

        <li>
          if your actions may cause any harm, damage or loss to the other Users
          or the Company, at our sole discretion.
        </li>
      </ol>

      <br />

      {/* INTELLECTUAL PROPERTY RIGHTS */}
      <h2 className="h5">INTELLECTUAL PROPERTY RIGHTS</h2>

      <br />
      <p>
        Unless expressly agreed to in writing, nothing contained herein shall
        give you a right to use any of the trade names, trademarks, service
        marks, logos, domain names, information, questions, answers, solutions,
        reports, and other distinctive brand features, save according to the
        provisions of these Terms of Use that shall be available on the
        Platform. All logos, trademarks, brand names, service marks, domain
        names, including material, designs, and graphics created by and
        developed by either the Platform or such other Third-Party and other
        distinctive brand features of the Platform are the property of the
        Platform or the respective copyright or trademark owner. Furthermore,
        concerning the Platform, we shall be the exclusive owner of all the
        designs, graphics, and the like, related to the Platform.
      </p>

      <br />

      <p>
        You shall not use any of the Intellectual Property displayed on the
        Platform in any manner that is likely to cause confusion among existing
        or prospective users of the Platform, or that in any manner disparages
        or discredits the Platform, to be determined in the sole discretion.
      </p>

      <br />

      <p>
        You are aware all Intellectual Property, including but not limited to
        copyrights, relating to said Services resides with the owners, and that
        at no point does any such Intellectual Property stand transferred from
        the aforementioned creators.
      </p>

      <br />

      <p>
        You are further aware that any reproduction or infringement of the
        Intellectual Property of the aforementioned owners by you will result in
        legal action being initiated against you by the respective owners of the
        Intellectual Property so reproduced/infringed upon. It is agreed to by
        you that the Contents of this section shall survive even after the
        termination or expiry of these Terms of Use and/or Privacy Policy.
      </p>

      <br />

      {/* DISCLAIMER OF WARRANTIES AND LIABALITIES */}
      <h2 className="h5">DISCLAIMER OF WARRANTIES AND LIABALITIES</h2>

      <br />

      <ol type="1" className={styles.insetList1}>
        <li>
          You further agree and undertake that you are accessing the Platform at
          your sole risk and that you are using the best and prudent judgment
          before availing of any features on the Platform or accessing/using any
          information displayed thereon.
        </li>

        <li>
          You agree that any kind of information, resources, activities, or
          recommendations obtained/availed from the Platform, written or oral,
          will not create any warranty and we disclaim all liabilities resulting
          from these.
        </li>

        <li>
          We do not guarantee that the features and content contained in the
          Platform will be uninterrupted or error-free, or that the Platform or
          its server will be free of viruses or other harmful components, and
          you hereby expressly accept any associated risks involved with your
          use of the Platform.
        </li>

        <li>
          It is further agreed to by you that the contents of this section shall
          survive even after the termination or expiry of the Terms of Use
          and/or Privacy Policy.
        </li>
      </ol>

      <br />

      {/* FORCE MAJEURE */}
      <h2 className="h5">FORCE MAJEURE</h2>

      <br />

      <p>
        We will not be liable for damages for any delay or failure to perform
        our obligations hereunder if such delay or failure is due to cause
        beyond our control or without its fault or negligence, due to force
        majeure events including but not limited to acts of war, acts of God,
        earthquake, riot, fire, festive activities sabotage, labor shortage or
        dispute, internet interruption, technical failure, breakage of sea
        cable, hacking, piracy, cheating, illegal or unauthorized.
      </p>

      <br />

      {/* DISPUTE RESOLUTION AND JURISDICTION */}
      <h2 className="h5">DISPUTE RESOLUTION AND JURISDICTION</h2>

      <br />

      <ol type="1" className={styles.insetList1}>
        <li>
          These Terms shall be governed and interpreted by and construed in
          accordance with the substantive Governing Law and subject to
          arbitration provisions below, each party hereby irrevocably and
          finally submits to the exclusive jurisdiction of the courts of{" "}
          <span className={styles.bold}>Ghaziabad, Uttar Pradesh, India,</span>
          where the Dispute Resolution will take place, thereto in respect of
          any disputes, legal action or proceedings arising out of or in
          connection with the Terms, interpretation, duties, performance,
          breach, etc. of these Terms.
        </li>

        <li>
          Should any Dispute arise out of or in connection with these Terms, the
          Parties hereto shall first endeavor to settle such Dispute amicably.
          If the Dispute is not resolved through amicable settlement within
          fifteen (15) days after commencement of discussions or such longer
          period as the Parties mutually agree in writing, then either Party may
          refer the Dispute for resolution by arbitration according to the
          provisions of the Arbitration and Conciliation Act, 1996 (India) or
          any statutory amendment or re-enactment thereof, or any statute
          enacted to replace the same, for the time being in force. The
          arbitration shall be conducted by a sole arbitrator appointed by
          mutual consent of the parties. The seat and venue of arbitration shall
          be in{" "}
          <span className={styles.bold}>Ghaziabad, Uttar Pradesh, India,</span>{" "}
          where the Dispute Resolution will take place, and the language of the
          proceedings shall be English.
        </li>

        <li>
          The Award rendered in any arbitration commenced hereunder shall be
          final and conclusive, and judgment thereon may be entered in any court
          having jurisdiction for its enforcement. The Parties undertake to
          implement the arbitration award. In addition, the Parties agree that
          no Party shall have any right to commence or maintain a suit or legal
          proceeding concerning a Dispute hereunder (other than for preventive
          or interlocutory relief pending completion of the arbitration
          proceedings under these Terms) until the Dispute has been determined
          in accordance with the arbitration procedure provided for herein and
          then only for the enforcement of the award rendered in such
          arbitration. When any Dispute is under arbitration, except for the
          matters under dispute, the Parties shall continue to exercise their
          remaining respective rights and fulfil their remaining respective
          obligations under these Terms.
        </li>
      </ol>

      <br />

      <h2 className="h5">MISCELLANEOUS PROVISIONS</h2>

      <br />

      <ol type="1" className={styles.insetList1}>
        <li>
          <span className={styles.bold}>Entire Agreement:</span> These Terms of
          Use, read with the Privacy Policy and Disclaimer form the complete and
          final contract between us with respect to the subject matter hereof
          and supersedes all other communications, representations, and
          agreements (whether oral, written, or otherwise) relating thereto.
        </li>

        <li>
          <span className={styles.bold}>Waiver:</span>The failure or delay on
          our part to enforce any provision of these Terms of Use at any time
          shall not be construed as a waiver of our right to enforce the same at
          a later stage. Similarly, any leniency shown in one or more instances
          shall not be interpreted as a continuing waiver of such provision or
          of any other provision of these Terms of Use.
        </li>

        <li>
          <span className={styles.bold}>Severability: </span>If any
          provision/clause of these Terms of Use is held to be invalid, illegal,
          or unenforceable by any court or authority of competent jurisdiction,
          the validity, legality, and enforceability of the remaining
          provisions/clauses of these Terms of Use shall in no way be affected
          or impaired thereby, and each such provision/clause of these Terms of
          Use shall be valid and enforceable to the fullest extent permitted by
          Applicable Law. In such case, these Terms of Use shall be reformed to
          the minimum extent necessary to correct any invalidity, illegality or
          unenforceability, while preserving to the maximum extent the original
          rights, intentions and commercial expectations of the Parties hereto,
          as expressed herein.
        </li>

        <li>
          <span className={styles.bold}>Contact Us:</span> If you have any
          questions about these Terms of Use, the practices of the Website, or
          your experience, you can contact us on mail@leondevs.tech.
        </li>
      </ol>
    </>
  );
};

const PrivacyPolicy = () => {
  return (
    <>
      <h1 className="h4">PRIVACY POLICY</h1>

      <br />

      <p className={styles.bold}>
        Welcome to M/s. Leondevs Tech (OPC) Private Limited.,’s Privacy Policy
        for Website
      </p>

      <br />

      <p>
        This Website is created and operated by M/s. Leondevs Tech (OPC) Private
        Limited.,. This legal agreement is an electronic record in terms of
        Indian Information Technology Act, 2000 and rules there under as
        applicable and the amended provisions about electronic records in
        various statutes as amended by the Indian Information Technology Act,
        2000. This electronic record is generated by a computer system and does
        not require any physical or digital signatures.
      </p>

      <br />

      <p>
        This legal document is published in accordance with the provisions of
        Rule 3 (1) of the Indian Information Technology (Intermediaries
        guidelines) Rules, 2011 and Rule 4 of the Information Technology
        (Reasonable security practices and procedures and sensitive personal
        data or information) Rules, 2011 of Information Technology Act, 2000
        amended through Information Technology Amendment Act, 2008 that require
        publishing the Terms of Services and practices for access or usage of{" "}
        <span className={styles.bold}>
          https://www.leondevs.tech/ (“website”).
        </span>
      </p>

      <br />

      <p>
        We take your privacy very seriously and hence the creator of this
        Privacy Policy ensures a steady commitment to Your privacy with regard
        to the protection of your invaluable information also to support the
        ongoing cause that you may share across on this Platform. We ask for
        this information so that we can understand more about the people who
        support us. This privacy policy contains information about the Website{" "}
        <span>“https://www.leondevs.tech/”</span> and is committed to
        maintaining the privacy of all the users.
      </p>

      <br />

      <p>
        To provide You with Our uninterrupted use of the Website, we may collect
        and, in some circumstances, disclose information about you with your
        permission. To ensure better protection of Your privacy, we provide this
        notice explaining Our information collection and disclosure policies,
        and the choices You make about the way Your information is collected and
        used.
      </p>

      <br />

      <hr />

      <p className={styles.bold}>
        This Privacy Policy shall be in compliance with the General Data
        Protection Regulation (GDPR) in effect from May 25, 2018, and any and
        all provisions that may read to the contrary shall be deemed to be void
        and unenforceable as of that date. If you do not agree with the terms
        and conditions of our Privacy Policy, including in relation to the
        manner of collection or use of your information, please do not use or
        access the Site. If you have any questions or concerns regarding this
        Privacy Policy, you should contact our Customer Care.
      </p>

      <hr />

      <br />

      <p>
        ANY CAPITALIZED WORDS USED HENCEFORTH SHALL HAVE THE MEANING ACCORDED TO
        THEM UNDER THIS AGREEMENT. FURTHER, ALL HEADING USED HEREIN ARE ONLY FOR
        THE PURPOSE OF ARRANGING THE VARIOUS PROVISIONS OF THE AGREEMENT IN ANY
        MANNER. NEITHER THE USER NOR THE CREATORS OF THIS PRIVACY POLICY MAY USE
        THE HEADING TO INTERPRET THE PROVISIONS CONTAINED WITHIN IT IN ANY
        MANNER.
      </p>

      <br />

      {/* INFORMATION WE COLLECT */}
      <h2 className="h5">INFORMATION WE COLLECT</h2>

      <br />

      <p>
        We are committed to respecting Your online privacy. We further recognize
        Your need for appropriate protection and management of any Personal
        Information You share with us. We may collect the following information:
      </p>

      <ol type="1" className={styles.insetList1}>
        <li>Personal data i.e. Email Id for verification purpose.</li>
        <li>
          Tracking Information such as, but not limited to the IP address of
          your device and Device ID when connected to the Internet. This
          information may include the URL that you just came from (whether this
          URL is on the Website or not), which URL you next go to (whether this
          URL is on the Website or not), your computer or device browser
          information, and other information associated with your interaction
          with the Website;
        </li>
        <li>Details of Website usage for analytics.</li>
      </ol>

      <br />

      <p>
        This privacy policy also applies to data we collect from users who are
        not registered as members of this Website, including, but not limited
        to, browsing behaviour, pages viewed etc. We also collect and store
        personal information provided by You from time to time on the Website.
        We only collect and use such information from you that we consider
        necessary for achieving a seamless, efficient and safe experience,
        customized to your needs including:{" "}
      </p>

      <ol type="1" className={styles.insetList1}>
        <li>To enable the provision of services opted for by you;</li>
        <li>To enable the viewing of content in your interest;</li>
        <li>
          To communicate the necessary account and service related information
          from time to time;
        </li>
        <li>
          To allow you to receive quality customer care services and data
          Collection;
        </li>
        <li>To comply with applicable laws, rules and regulations;</li>
      </ol>

      <br />

      <p>
        Where any service requested by You involves a third party, such
        information as is reasonably necessary by the Website to carry out Your
        service request may be shared with such third party. The Website may
        also use contact information internally to direct its efforts for
        service improvement but shall immediately delete all such information
        upon withdrawal of your consent for the same through the ‘unsubscribe’
        button or through an email to be sent to mail@leondevs.tech
      </p>

      <br />

      <p>
        To the extent possible, we provide You with the option of not divulging
        any specific information that you wish for us not to collect, store or
        use. You may also choose not to use a particular service or feature on
        the Website and opt-out of any non-essential communications from the
        Website.
      </p>

      <br />

      <p>
        Further, transacting over the internet has inherent risks which can only
        be avoided by you following security practices yourself, such as not
        revealing account/login related information to any other person and
        informing our customer care team about any suspicious activity or where
        your account has/may have been compromised.
      </p>

      <br />

      {/* OUR USE OF YOUR INFORMATION */}
      <h2 className="h5">OUR USE OF YOUR INFORMATION</h2>

      <br />

      <p>
        The information provided by you shall be used to provide and improve the
        service for you and all users.
      </p>

      <ol type="1" className={styles.insetList1}>
        <li>To provide and help you with services on your request.</li>
        <li>For maintaining an internal record.</li>
        <li>For enhancing the Services provided.</li>
        <li>
          For maintaining record under the legal and statutory provisions.
        </li>
      </ol>

      <br />

      <p>
        For more details about the nature of such communications, please refer
        to our Terms of Service. Further, your data and Sensitive Personal data
        may be collected and stored by Us for internal record.
      </p>

      <br />

      <p>
        We use Your tracking information such as IP addresses, and or Device ID
        to help identify you and to gather broad demographic information and
        make further services available to you. We will not sell, license or
        trade Your personal information. We will not share your personal
        information with others unless they are acting under our instructions or
        we are required to do so by law.
      </p>

      <br />

      <p>
        Information collected via Our server logs includes users' IP addresses
        and the pages visited; this will be used to manage the web system and
        troubleshoot problems. We also use third-party analytics, tracking,
        optimization and targeting tools to understand how users engage with our
        Website so that we can improve it and cater personalized content
        according to their preferences.
      </p>

      <br />

      {/* HOW INFORMATION IS COLLECTED */}
      <h2 className="h5">HOW INFORMATION IS COLLECTED</h2>

      <br />

      <p>
        Before or at the time of collecting personal information, we will
        identify the purposes for which information is being collected. If the
        same is not identified to you, you have the right to request the Website
        to elucidate the purpose of collection of said personal information,
        pending the fulfilment of which you shall not be mandated to disclose
        any information whatsoever.{" "}
      </p>

      <br />

      <p>
        We will collect and use your personal information solely to fulfil those
        purposes specified by us, within the scope of the consent of the
        individual concerned or as required by law. We will only retain personal
        information as long as necessary for the fulfilment of those purposes.
        We will collect personal information by lawful and fair means and with
        the knowledge and consent of the individual concerned.
      </p>

      <br />

      <p>
        Personal data should be relevant to the purposes for which it is to be
        used, and, to the extent necessary for those purposes, should be
        accurate, complete, and up-to-date.
      </p>

      <br />

      {/* EXTERNAL LINKS ON THE WEBSITE */}
      <h2 className="h5">EXTERNAL LINKS ON THE WEBSITE</h2>

      <br />

      <p>
        The Website may include hyperlinks to other Websites or resources. We
        have no control over any other website or resources or contents
        available on these other websites, which are provided by companies or
        persons other than Us. You acknowledge and agree that we are not
        responsible for the availability of any such external sites or
        resources, and do not endorse any advertising, service(s) or other
        materials on or available from such Website or resources. You
        acknowledge and agree that We are not liable for any loss or damage
        which may be incurred by you as a result of the availability of those
        external sites or resources, or as a result of any reliance placed by
        you on the completeness, accuracy or existence of any advertising,
        services or other materials on, or available from, such Websites. These
        external third party websites and resource providers may have their
        privacy policies governing the collection, storage, retention and
        disclosure of Your Personal Information that You may be subject to. We
        recommend that you enter the Website and review their privacy policy.
      </p>

      <br />

      {/* YOUR RIGHTS */}
      <h2 className="h5">YOUR RIGHTS</h2>

      <br />

      <p>
        Unless subject to an exemption, you have the following rights concerning
        your data:{" "}
      </p>

      <ol type="1" className={styles.insetList1}>
        <li>
          The right to request a copy of your data which we hold about you;
        </li>
        <li>
          The right to request for any correction to any personal data if it is
          found to be inaccurate or out of date;
        </li>
        <li>
          The right to withdraw your consent to the processing of the data at
          any time;
        </li>
        <li>The right to object to the processing of personal data;</li>
        <li>The right to complain about a supervisory authority. </li>
        <li>
          The right to obtain information as to whether personal data are
          transferred to a third country or an international organization.
        </li>
      </ol>

      <br />

      <p>
        Where you hold an account with any of our services, you are entitled to
        a copy of all personal data which we hold concerning you. You are also
        entitled to request that we restrict how we use your data in your
        account when you log in.
      </p>

      <br />

      {/* CONFIDENTIALITY */}
      <h2 className="h5">CONFIDENTIALITY</h2>

      <br />

      <p>
        You further acknowledge that the Website may contain information which
        is designated confidential by us and that you shall not disclose such
        information without our prior written consent. Your information is
        regarded as confidential and therefore will not be divulged to any third
        party, unless if legally required to do so to the appropriate
        authorities. We will not sell, share, or rent your personal information
        to any third party or use your e-mail address for unsolicited mail. Any
        emails sent by us will only be in connection with the provision of
        agreed services, and you retain sole discretion to seek for
        discontinuation of such communications at any point of time.{" "}
      </p>

      <br />

      {/* OTHER INFORMATION COLLECTORS */}
      <h2 className="h5">OTHER INFORMATION COLLECTORS</h2>

      <br />

      <p>
        Except as otherwise expressly included in this Privacy Policy, this
        document only addresses the use and disclosure of information we collect
        from you. To the extent that you disclose your information to other
        parties, whether they are on our Website or other sites throughout the
        Internet, different rules may apply to their use or disclosure of the
        information you disclose to them. Since we do not control the privacy
        policies of the third parties, you are subject to ask questions before
        you disclose your personal information to others.{" "}
      </p>

      <br />

      {/* OUR DISCLOSURE OF YOUR INFORMATION */}
      <h2 className="h5">OUR DISCLOSURE OF YOUR INFORMATION</h2>

      <br />

      <p>
        We may host surveys for survey creators for our Website who are the
        owners and users of your survey responses. We do not own or sell your
        responses. Anything you expressly disclose in your responses will be
        disclosed to survey creators. Please contact the survey creator directly
        to better understand how they might share your survey responses.
      </p>

      <br />

      <p>
        Information collected will not be considered as sensitive if it is
        freely available and accessible in the public domain or is furnished
        under the Right to Information Act, 2005, any rules made thereunder or
        any other law for the time being in force.
      </p>

      <br />

      <p>
        Due to the existing regulatory environment, we cannot ensure that all of
        your private communications and other personally identifiable
        information will never be disclosed in ways not otherwise described in
        this Privacy Policy. By way of example (without limiting and foregoing),
        we may be forced to disclose information to the government, law
        enforcement agencies or third parties. Therefore, although we use
        industry-standard practices to protect your privacy, we do not promise,
        and you should not expect, that your personally identifiable information
        would always remain private. We do however assure you that any
        disclosure of your personally identifiable information shall be
        personally intimated to you through an email sent to your provided email
        address.
      </p>

      <br />

      <p>
        As a matter of policy, we do not sell or rent any personally
        identifiable information about you to any third party. However, the
        following describes some of the ways that your personally identifiable
        information may be disclosed:{" "}
      </p>

      <ol className={styles.insetList1} type="1">
        <li>
          External Service Providers: There may be several services offered by
          external service providers that help you use our Website. If you
          choose to use these optional services, and in the course of doing so,
          disclose information to the external service providers, and/or permit
          them to collect information about you, then their use of your
          information is governed by their privacy policy
        </li>
        <li>
          Law and Order: We cooperate with law enforcement inquiries, as well as
          other third parties to enforce laws, such as intellectual property
          rights, fraud and other rights. We can (and you authorize us to)
          disclose any information about you to law enforcement where the FIR is
          filed against the user and other government officials as we, in our
          sole discretion, believe necessary or appropriate, in connection with
          an investigation of fraud, intellectual property infringements, or
          other activity that is illegal or may expose us or you to legal
          liability.
        </li>
      </ol>

      <br />

      {/* ACCESSING, REVIEWING AND CHANGING YOUR PROFILE */}
      <h2 className="h5">ACCESSING, REVIEWING AND CHANGING YOUR PROFILE</h2>

      <br />

      <p>
        Following registration, you can review and change the information you
        submitted at the stage of registration, except Email ID, mobile number
        and PAN card. An option for facilitating such change shall be present on
        the Website and such change shall be facilitated by the User. If you
        change any information, we may or may not keep track of your old
        information. We will not retain in our files information you have
        requested to remove for certain circumstances, such as to resolve
        disputes, troubleshoot problems and enforce our terms and conditions.
        Such prior information shall be completely removed from our databases,
        including stored ‘back up’ systems. If you believe that any information,
        we are holding on you is incorrect or incomplete, or to remove your
        profile so that others cannot view it, the User needs to remediate, and
        promptly correct any such incorrect information.
      </p>

      <br />

      {/* CONTROL OF YOUR PASSWORD */}
      <h2 className="h5">CONTROL OF YOUR PASSWORD</h2>

      <br />

      <p>
        You are entirely responsible for maintaining the confidentiality of your
        password. You must protect it against unauthorized access of your
        account and information by choosing your password carefully and keeping
        your password and computer secure by signing out after using our
        services
      </p>

      <br />

      <p>
        You agree not to use the account, username, email address or password of
        another Member at any time or to disclose your password to any third
        party. You are responsible for all actions taken with your login
        information and password, including fees. If you lose control of your
        password, you may lose substantial control over your personally
        identifiable information and may be subject to legally binding actions
        taken on your behalf. Therefore, if your password has been compromised
        for any reason, you should immediately change your password. You agree
        to notify us immediately if you suspect any consistent unauthorized use
        of your account or access to your password even after changing it.
      </p>

      <br />

      {/* SECURITY */}
      <h2 className="h5">SECURITY</h2>

      <br />

      <p>
        We treat data as an asset that must be protected against loss and
        unauthorized access. We employ many different security techniques to
        protect such data from unauthorized access by members inside and outside
        the Website. We follow generally accepted industry standards to protect
        the Personal Information submitted to us and information that we have
        accessed.
      </p>

      <br />

      <p>
        However, as effective as encryption technology is, no security system is
        impenetrable. Our Website cannot guarantee the security of our database,
        nor can we guarantee that information you provide will not be
        intercepted while being transmitted to the Website over the Internet.
      </p>

      <br />

      {/* SEVERABILITY */}
      <h2 className="h5">SEVERABILITY</h2>

      <br />

      <p>
        Each paragraph of this Privacy Policy shall be and remain separate from
        and independent of and severable from all and any other paragraphs
        herein except where otherwise expressly indicated or indicated by the
        context of the agreement. The decision or declaration that one or more
        of the paragraphs are null and void shall not affect the remaining
        paragraphs of this privacy policy.
      </p>

      <br />

      {/* AMENDMENT */}
      <h2 className="h5">AMENDMENT</h2>

      <br />

      <p>
        Our Privacy Policy may change from time to time. The most current
        version of the policy will govern our use of your information and will
        always be at the Website. Any amendments to this Policy shall be deemed
        as accepted by the User on their continued use of the Website.
      </p>

      <br />

      {/* CONSENT WITHDRAWAL, DATA DOWNLOAD & DATA REMOVAL REQUESTS */}
      <h2 className="h5">
        CONSENT WITHDRAWAL, DATA DOWNLOAD & DATA REMOVAL REQUESTS
      </h2>

      <br />

      <p>
        To withdraw your consent, or to request the download or delete your data
        with us for any or all our services at any time, please email to
        mail@leondevs.tech{" "}
      </p>

      <br />

      {/* CONTACT US */}
      <h2 className="h5">CONTACT US</h2>

      <br />

      <p>
        If you have any questions or concerns regarding this privacy policy, you
        should contact us by sending an e-mail to please email to
        mail@leondevs.tech
      </p>
    </>
  );
};

function legal() {
  return (
    <div className={styles.pageContainer}>
      <TermsOfUse />

      <br />
      <hr className={styles.sepration} />
      <br />

      <PrivacyPolicy />
    </div>
  );
}

export default legal;
